#! /bin/bash
network=`nmcli -t -f name connection show --active`
if [[ $network = "BITS-(STUDENT|STAFF)" ]]
then
	username="F20190411"
	password="B3PS045604#"

	time=`date +%s%N | cut -b1-13`

	url="https://fw.bits-pilani.ac.in:8090/httpclient.html"

	args="mode=191&username=${username}&password=${password}&a=${time}&producttype=0"

	curl --data-urlencode $args $url
fi
